### ISSUE TITLE
Publishing broken after 0.37.x

### ISSUE THREAD

**Issue by musketyr** [kordamp/kordamp-gradle-plugins#343]
Hi,

I have a problem with publishing using Bintray and releasing GitHub Pages since 0.37.0. 

The latest stable version seems to be `0.36.0`.

Example build - https://github.com/agorapulse/testing-libraries/runs/761129719?check_suite_focus=true

```
> Configure project :
Kordamp Gradle plugins 0.37.1. Consider becoming a patron at https://www.patreon.com/aalmiray

> Task :aggregateConvertCodeToHtml
> Task :aggregateGenerateSourceHtmlOverview
> Task :aggregateSourceHtml
> Task :aggregateSourceXref
> Task :guide:asciidoctor
> Task :guide:createGuide
> Task :guide:gitPublishReset
> Task :guide:gitPublishCopy
> Task :guide:gitPublishCommit
> Task :guide:gitPublishPush
> Task :fixt:bintrayUpload SKIPPED
> Task :grails-job-testing-support:bintrayUpload SKIPPED
> Task :office-unit:bintrayUpload SKIPPED
> Task :spock:bintrayUpload SKIPPED
> Task :bintrayUpload SKIPPED
> Task :bintrayPublish
close() called when useCnt is already zero for Repository[/home/runner/work/testing-libraries/testing-libraries/docs/guide/build/gitPublish/.git]

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings
```

**Comment by aalmiray** [comment]
There were internal changes in these commits
https://github.com/kordamp/kordamp-gradle-plugins/commit/4796e67319a92386d39c77ff1f59a1ea8265accc
https://github.com/kordamp/kordamp-gradle-plugins/commit/5b13d969e39f25d0c97edc791668d7287dfd7e11
https://github.com/kordamp/kordamp-gradle-plugins/commit/00f0326c006cccb9a25a1ccdbdcb701821c49c8e

Which caused issues in `0.37.0` and `0.37.1`. I thought they were fixed in `0.38.0`. Di you try that last version as well?

**Comment by aalmiray** [comment]
I can confirm `0.38.0` fixed the problem as kordamp-parentpom `1.17.0` used that version to publish to GPP and Bintray

https://github.com/kordamp/kordamp-parentpom/blob/master/gradle.properties
https://bintray.com/kordamp/maven/kordamp-parentpom/1.17.0

**Comment by musketyr** [comment]
still the same - https://github.com/agorapulse/testing-libraries/runs/761222592?check_suite_focus=true

**Comment by aalmiray** [comment]
Huh, OK. I missed something else then. Will have a look asap.

**Comment by musketyr** [comment]
so it could be related to the dependency versions?

https://github.com/agorapulse/testing-libraries/blob/master/settings.gradle#L30-L45

**Comment by aalmiray** [comment]
I don't think so. Querying the plugin set using `gw :spock:plugins` yields

    plugin 19:
        id: org.kordamp.gradle.plugin.bintray.BintrayPlugin
        implementationClass: org.kordamp.gradle.plugin.bintray.BintrayPlugin
        enabled: false

This means the plugin was applied but it's disabled. I think `org.kordamp.gradle.bintray` now requires explicit enabling on a target project, it's no longer enough to have the plugin in the classpath and applied.

    config {
        bintray {
            enabled = true
            name = subproject.name
            githubRepo = "agorapulse/$rootProject.name"
        }
    }

This solves the problem. I didn't detect this before as all my projects explicitly enabled bintray. Sorry about that.

**Comment by musketyr** [comment]
ah, ok, thanks!

**Comment by musketyr** [comment]
it's actually my fault as well, I do so in different projects but I've forgotten for these ones

**Comment by aalmiray** [comment]
No worries then, we figured it out 😄

**Comment by aalmiray** [comment]
Is there anything else left to do for this issue?

**Comment by musketyr** [comment]
No, thanks
